### ISSUE TITLE
Add search endpoints to paginate data

### ISSUE THREAD

**Issue by tannerz28** [Nightwatch/-DEPRECATED-api#148]
Current GET endpoints get ALL data from the database. Some tables will grow very large, so requests should be paginated to limit the size of the response.

Maybe also make the routes that GET all rows only accessible to the bot to prevent api spam?

Search routes would look like

/api/<controller>/search?skip=20&take=10

Look at the searchFriendRequests method to see how it should be done.

**Comment by jasonhaxstuff** [comment]
How would you make it only accessible to people with the token? I know you already have a system for that, but how does the API make sure?

**Comment by tannerz28** [comment]
I havent decided if Im going to make the get all row endpoints private or not.

If I do it, I would have to create a decorator or function that validates the JWT token in that endpoint.

It could be an argument to make the entire api private, but that wouldnt be any fun.

**Comment by jasonhaxstuff** [comment]
yeah, cuz then people like me would need to shut down their guis lol
